<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsPublishable>false</IsPublishable>
    <GenerateProgramFile>false</GenerateProgramFile>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="SummaryTests.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Expecto" Version="11.0.0-alpha8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\CLI\ARCSummary.fsproj" />
  </ItemGroup>

</Project>
